export const styles = {
    page: { maxWidth: 900, margin: "40px auto", padding: 16, fontFamily: "system-ui" },
    header: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 },
    inputRow: { marginTop: 12, display: "flex", gap: 8, alignItems: "center" },
    input: {
        flex: 1,
        padding: 10,
        fontSize: 16,
        minHeight: 22,
        maxHeight: 160,
        overflowY: "auto" as const,
        resize: "none" as const,
    },
    button: {
        padding: "10px 14px",
        background: "#2563eb",
        color: "#fff",
        border: "1px solid #1d4ed8",
        borderRadius: 8,
        alignSelf: "center",
        height: 40,
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
    },
    clearButton: {
        padding: "10px 14px",
        borderRadius: 8,
        border: "1px solid #ddd",
        background: "#fff",
        alignSelf: "center",
        height: 40,
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
    },
    errorBox: { marginTop: 12, padding: 12, background: "#ffe6e6", border: "1px solid #ffb3b3" },
    latestResponseSection: { marginTop: 12, padding: 12, border: "1px solid #ddd", borderRadius: 10, background: "#fcfcfc" },
    latestResponseTitle: { margin: 0, fontSize: 16 },
    latestResponseBody: {
        marginTop: 8,
        whiteSpace: "pre-wrap",
        lineHeight: 1.5,
        minHeight: 72,
        maxHeight: 180,
        overflowY: "auto" as const,
    },
    historySection: { marginTop: 12, padding: 12, border: "1px solid #ddd", borderRadius: 10 },
    historyHeader: { marginTop: 2, padding: "0 0 8px 0", display: "flex", justifyContent: "space-between", alignItems: "center" },
    emptyState: { opacity: 0.7 },
    historyList: { display: "flex", flexDirection: "column", gap: 12 },
    historyCard: { border: "1px solid #ddd", borderRadius: 10, padding: 12 },
    historyTime: { fontSize: 12, opacity: 0.7 },
    historyPromptWrap: { marginTop: 8 },
    historyResponseWrap: { marginTop: 8 },
    responseToggle: {
        marginTop: 6,
        width: "100%",
        textAlign: "left",
        border: "1px solid #ddd",
        borderRadius: 8,
        padding: 10,
        background: "#fafafa",
        cursor: "pointer",
        font: "inherit",
        color: "inherit",
    },
    responseHint: { marginTop: 8, fontSize: 12, opacity: 0.7 },
    preWrap: { whiteSpace: "pre-wrap" },
} as const;

export const promptPageCss = `
.prompt-input::placeholder {
    font-size: 14px;
}
`;
